# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3e451f8d4f647b392a3965937e5904e6282645dcfeb0ff8099f58d1e0acbdc1a9b7d8ebb946e586ea15f1b1aefedfa78681076e38eeb7e833104aad2ecc7347

test:
  secret_key_base: 007bcfb0450c0f3d85ca1e9f0f4f607ef7c424ec544fb80be1960200c9ada17668b2ac94078648ddd10040139857dc0feed1331cc56b0cf963a3558908171566

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
